# Site settings
title: Hoang Duong blog
email: hduong@berkeley.edu 
description: "Learning Machine Learning"
baseurl: ""
url: "http://hduongtrong.github.io"
twitter_username: hduongtrong
github_username:  hduongtrong

# Build settings
markdown: redcarpet
permalink: pretty
